In [1]:
# Importar libreria
import pandas as pd

In [2]:
# Cargando mis datos como dataframe
data = pd.read_csv("notes.csv")

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
# Visualizar los 5 primeros renglones
data.head()

    Nombre  nota
0  Araceli     9
1   Manuel     5
2    Pablo     7
3    Iñigo     4
4    Mario     3

In [5]:
#Utilizando head con más renglones
data.head(6)

    Nombre  nota
0  Araceli     9
1   Manuel     5
2    Pablo     7
3    Iñigo     4
4    Mario     3
5     Raul     4

In [6]:
# Función que me permite ver la estadistica descriptiva de las columnas numericas de mi dataset
data.describe()

            nota
count  13.000000
mean    5.615385
std     2.364264
min     2.000000
25%     4.000000
50%     5.000000
75%     7.000000
max    10.000000

In [7]:
# USANDO PANDAS
#Calculo de la media
media = data["nota"].mean()
media

5.615384615384615

In [8]:
#Calculo de la mediana
mediana = data["nota"].median()
mediana

5.0

In [11]:
#Calculo de la moda
moda = data["nota"].mode()
print(moda)

0    4
Name: nota, dtype: int64

In [12]:
#Calculo del rango
rango = data["nota"].max() - data["nota"].min()
rango

8

In [16]:
#USANDO NUMPY
import numpy as np
import scipy as stats

In [14]:
np.mean(data["nota"])

5.615384615384615

In [15]:
np.median(data["nota"])

5.0

In [ ]:
# Agregando varianza y desviación estandar
perros = [600,470,170,430,300]

In [ ]:
np.mean(perros)

394.0

In [ ]:
np.median(perros)

430.0

In [ ]:
np.var(perros)

21704.0

In [ ]:
np.std(perros)

147.32277488562318